# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20160505_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='email',
        ),
    ]
