# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20160509_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='abc', max_length=128),
        ),
    ]
