# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='guest', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(default='guest', max_length=12, unique=True),
        ),
    ]
