# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20160513_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('username',)]),
        ),
    ]
