# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betline',
            old_name='over_under',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='betline',
            old_name='time',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='betline',
            name='over',
        ),
        migrations.RemoveField(
            model_name='betline',
            name='under',
        ),
        migrations.AddField(
            model_name='wager',
            name='over_OR_under',
            field=models.CharField(choices=[('over', 'over'), ('under', 'under')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='betline',
            name='key_phrase',
            field=models.TextField(default='hello'),
        ),
        migrations.AlterField(
            model_name='wager',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
