# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0002_auto_20160513_0557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='betline',
            unique_together=set([('key_phrase', 'amount', 'duration')]),
        ),
        migrations.AlterUniqueTogether(
            name='wager',
            unique_together=set([('amount', 'player', 'betline', 'over_OR_under')]),
        ),
    ]
