# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0003_auto_20160514_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betline',
            name='key_phrase',
            field=models.CharField(default='hello', max_length=40),
        ),
    ]
