# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0005_auto_20160515_0658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wager',
            unique_together=set([]),
        ),
    ]
