# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0006_auto_20160515_0704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wager',
            unique_together=set([('amount', 'player', 'betline', 'over_OR_under')]),
        ),
    ]
