# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0007_auto_20160516_0153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='betline',
            unique_together=set([('key_phrase', 'amount', 'duration')]),
        ),
    ]
